# .github/dependabot.yml
---
version: 8
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "react"
        versions: [">=20.0.0"] # Ignore React 20 and above
      - dependency-name: "next"
        versions: [">=16.0.0"] # Ignore Next.js 16 and above
